### ISSUE TITLE
where is “distributed_train.sh” in the eval.sh in the project

### ISSUE THREAD

**Issue by BigbigVegetable** [zhoudaquan/dvit_repo#3]
where is “distributed_train.sh” in the eval.sh in the project，please?
![image](https://user-images.githubusercontent.com/39050018/115558048-e600fe00-a2e4-11eb-937d-900754343de1.png)

**Comment by zhoudaquan** [comment]
> where is “distributed_train.sh” in the eval.sh in the project，please?
> ![image](https://user-images.githubusercontent.com/39050018/115558048-e600fe00-a2e4-11eb-937d-900754343de1.png)

Hi,

Just added. Please see the updated repo. Thanks.

**Comment by BigbigVegetable** [comment]
ok .Thank you.
